const TIER_COLORS = {
  Platinum: "bg-purple-100 text-purple-700 border-purple-200",
  Gold: "bg-yellow-100 text-yellow-700 border-yellow-200",
  Silver: "bg-gray-100 text-gray-600 border-gray-200",
  Unrated: "bg-gray-50 text-gray-400 border-gray-100",
};

export default function CompetitiveTab({ competitive, dealer, intLoading }) {
  if (intLoading) return (<div className="flex items-center justify-center py-16"><div className="w-8 h-8 border-4 border-teal-100 border-t-[#1A9988] rounded-full animate-spin" /></div>);
  return (<div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="bg-white rounded-2xl p-5 shadow-sm text-center"><p className="text-sm text-gray-500 mb-1">Your Market Rank</p><div className="text-4xl font-bold" style={{ color: "#1A9988" }}>#{competitive?.my_rank}</div><p className="text-sm text-gray-400">out of {competitive?.total_dealers} dealers</p></div><div className="bg-white rounded-2xl p-5 shadow-sm text-center"><p className="text-sm text-gray-500 mb-1">Your Avg Days to Sell</p><div className="text-4xl font-bold" style={{ color: competitive?.my_avg_days_to_sell <= competitive?.market_avg_days_to_sell ? "#16a34a" : "#ef4444" }}>{competitive?.my_avg_days_to_sell > 0 ? `${competitive.my_avg_days_to_sell}d` : "—"}</div><p className="text-sm text-gray-400">Market avg: {competitive?.market_avg_days_to_sell > 0 ? `${competitive.market_avg_days_to_sell}d` : "—"}</p></div><div className="bg-white rounded-2xl p-5 shadow-sm text-center"><p className="text-sm text-gray-500 mb-1">Your Views vs Top 10</p><div className="text-4xl font-bold" style={{ color: "#d97706" }}>{competitive?.my_total_views}</div><p className="text-sm text-gray-400">Top 10 avg: {Math.round(competitive?.top10_avg_views || 0)}</p></div></div><div className="bg-white rounded-2xl p-5 shadow-sm"><h2 className="font-bold text-gray-900 mb-4">Dealer Leaderboard</h2><div className="space-y-2">{competitive?.all_dealers?.map((d, i) => { const isMe = d.id === dealer.id; return (<div key={d.id} className={`flex items-center gap-3 p-3 rounded-xl ${isMe ? "border-2 border-teal-400 bg-teal-50" : "bg-gray-50"}`}><span className={`w-7 h-7 rounded-full text-sm font-bold flex items-center justify-center flex-shrink-0 ${i === 0 ? "bg-yellow-400 text-white" : i === 1 ? "bg-gray-300 text-white" : i === 2 ? "bg-orange-400 text-white" : "bg-gray-200 text-gray-600"}`}>{i + 1}</span><div className="flex-1 min-w-0"><p className="font-medium text-gray-900 text-sm truncate">{d.business_name} {isMe && (<span className="text-teal-600 text-xs">(You)</span>)}</p><div className="flex gap-3 mt-0.5"><span className="text-xs text-gray-400">{d.active_count} active</span><span className="text-xs text-gray-400">{d.total_sold} sold</span><span className="text-xs text-gray-400">{d.total_views} views</span></div></div><div className="text-right"><p className="text-sm font-bold" style={{ color: "#1A9988" }}>{d.listing_integrity_score}</p><span className={`text-xs px-1.5 py-0.5 rounded-full ${TIER_COLORS[d.score_tier]?.split(" ")[0]} ${TIER_COLORS[d.score_tier]?.split(" ")[1]}`}>{d.score_tier}</span></div></div>); })}</div></div></div>);
}




