import EmptyState from "./EmptyState";
import ScoreBar from "./ScoreBar";

export default function PricingTab({ activeVehicles, intLoading }) {
  if (intLoading) return (<div className="flex items-center justify-center py-16"><div className="w-8 h-8 border-4 border-teal-100 border-t-[#1A9988] rounded-full animate-spin" /></div>);
  return (<div className="space-y-4"><div className="bg-white rounded-2xl p-5 shadow-sm"><h2 className="font-bold text-gray-900 mb-1">Market Price Intelligence</h2><p className="text-sm text-gray-500 mb-4">How each listing compares to similar cars in the market</p>{activeVehicles.length === 0 ? (<EmptyState icon="💰" text="No active listings to analyse." />) : (activeVehicles.map((v) => { const intel = v.price_intel; if (!intel || !intel.avg_price) return (<div key={v.id} className="p-4 bg-gray-50 rounded-xl mb-3"><p className="font-medium text-gray-900">{v.year} {v.make} {v.model}</p><p className="text-sm text-gray-400 mt-1">Not enough similar listings to compare.</p></div>); const pct = intel.pct_vs_market; return (<div key={v.id} className="border border-gray-100 rounded-xl p-4 mb-3"><div className="flex items-center justify-between mb-3"><div><p className="font-bold text-gray-900">{v.year} {v.make} {v.model}</p><p className="text-xl font-bold mt-0.5" style={{ color: "#1A9988" }}>AED {v.price_aed?.toLocaleString()}</p></div><span className={`px-3 py-1.5 rounded-xl text-sm font-bold ${pct > 0 ? "bg-red-50 text-red-600" : pct < 0 ? "bg-green-50 text-green-600" : "bg-gray-50 text-gray-600"}`}>{pct === 0 ? "At market" : pct > 0 ? `+${pct}% above` : `${pct}% below`}</span></div><div className="grid grid-cols-3 gap-3 mb-3"><div className="text-center p-2 bg-gray-50 rounded-lg"><p className="text-sm font-bold text-gray-900">AED {intel.min_price?.toLocaleString()}</p><p className="text-xs text-gray-400">Lowest</p></div><div className="text-center p-2 rounded-lg" style={{ background: "#f0faf9" }}><p className="text-sm font-bold" style={{ color: "#1A9988" }}>AED {intel.median_price?.toLocaleString()}</p><p className="text-xs text-gray-400">Median</p></div><div className="text-center p-2 bg-gray-50 rounded-lg"><p className="text-sm font-bold text-gray-900">AED {intel.max_price?.toLocaleString()}</p><p className="text-xs text-gray-400">Highest</p></div></div>{intel.recommended_min && (<div className={`p-3 rounded-lg ${intel.in_competitive_range ? "bg-green-50" : "bg-orange-50"}`}><p className={`text-xs font-medium ${intel.in_competitive_range ? "text-green-700" : "text-orange-700"}`}>{intel.in_competitive_range ? "✅ Price is within competitive range" : `💡 Recommended: AED ${intel.recommended_min?.toLocaleString()} — ${intel.recommended_max?.toLocaleString()}`}</p></div>)}<p className="text-xs text-gray-400 mt-2">{intel.similar_count} similar cars</p></div>); }))}</div></div>);
}




